# Generated by Django 6.0 on 2026-03-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_usertype_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcategory', models.CharField(max_length=20)),
                ('pcompany', models.CharField(max_length=20)),
                ('pname', models.CharField(max_length=20)),
                ('pprice', models.IntegerField()),
                ('pdesc', models.TextField()),
                ('pimage', models.ImageField(default='', upload_to='product/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
