# Generated by Django 6.0 on 2026-03-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pcategory',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcompany',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pname',
            field=models.CharField(max_length=50),
        ),
    ]
