# Generated by Django 6.0 on 2026-03-26 11:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='ttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.PositiveBigIntegerField()),
                ('qty', models.PositiveBigIntegerField(default=1)),
                ('payment', models.BooleanField(default='False')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
