# Generated by Django 6.0 on 2026-03-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_wishlist_ttime_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
